server.port=8082
spring.application.name=ms-scrum-core
spring.datasource.url=jdbc:postgresql://localhost:5432/db_scrum_core
spring.datasource.username=scrum_core_app
spring.datasource.password=pwd_access_123
spring.docker.compose.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true