spring.application.name=api-gateway

server.port=8080

security.jwt.secret=${JWT_SECRET:zqdXnYkV3BKJ7KCVv2aScsgoHOzw6MNdNFw0HMtF6FjnP7IeAGjQthso016Hfv0H}

# Using the required Spring Boot 4.x / Cloud 2025 prefix
# Updated Route with RewritePath
spring.cloud.gateway.server.webflux.routes[0].id=user-access-service
# Use the direct URL instead of lb://
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=api/auth/**
# This line strips "/test" and just sends the rest (e.g., "/get") to the target

spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/projet/**


spring.cloud.gateway.server.webflux.routes[1].id=test-route
spring.cloud.gateway.server.webflux.routes[1].uri=https://httpbin.org
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/test/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/test/(?<segment>.*), /$\{segment}

spring.cloud.discovery.enabled=false

security.jwt.public-paths=/auth/**,/v3/api-docs/**,/swagger-ui/**,/test/**,/login,/auth/register,/auth/refresh