version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: agile-tracker-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_admin_password
    volumes:
      # Ceci copie ton fichier SQL dans le dossier magique d'initialisation de Docker
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Ceci sauvegarde tes données sur ton disque dur pour ne pas les perdre si le conteneur s'arrête
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: