package com.agile_tracker.user_access_ms.dtos.projects;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserAssignmentDTO {
    // These 3 fields are all the Project MS needs to create a relationship
    private Integer userId;     // The ID generated by your Database
    private Integer projetId; // The ID from the frontend request
    private String role;     // The role (e.g., "DEVELOPER", "SCRUM_MASTER")
}