spring.application.name=api-gateway

server.port=${SERVER_PORT:8082}

security.jwt.secret=${JWT_SECRET:change-me-use-a-strong-secret-at-least-32-bytes-long}

# Using the required Spring Boot 4.x / Cloud 2025 prefix
# Updated Route with RewritePath
spring.cloud.gateway.server.webflux.routes[0].id=user-access-service
# Use the direct URL instead of lb://
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*), /$\{segment}
# This line strips "/test" and just sends the rest (e.g., "/get") to the target


spring.cloud.gateway.server.webflux.routes[1].id=test-route
spring.cloud.gateway.server.webflux.routes[1].uri=https://httpbin.org
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/test/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/test/(?<segment>.*), /$\{segment}

spring.cloud.discovery.enabled=false

security.jwt.public-paths=/auth/**,/v3/api-docs/**,/swagger-ui/**,/test/**,/login,/auth/register,/auth/refresh