version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db_user_access
      POSTGRES_USER: user_access_app
      POSTGRES_PASSWORD: pwd_access_123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-access-ms:
    build: .
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/db_user_access
      DB_USERNAME: user_access_app
      DB_PASSWORD: pwd_access_123
      JWT_SECRET: zqdXnYkV3BKJ7KCVv2aScsgoHOzw6MNdNFw0HMtF6FjnP7IeAGjQthso016Hfv0H
      JWT_ACCESS_EXPIRATION_MS: 300000
      JWT_REFRESH_EXPIRATION_MS: 604800000
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pgdata:
